language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install: cd ./api
install:
  - npm install
script:
  - npm run lint
  - npm run test:coveralls
  - npm run test

notifications:
  email: false